added speakers!!
techlahoma/thunderplains-2020 pull request #16
Opened 2020-10-30 03:44 UTC by kendallcorner

Please review and give feedback. I am also open to other things! Emily can add twitter handles later.

2020-10-30 17:21 UTC, maxxcrawford requested changes
Requested changes:

- [ ] Add more speaker info (Company name, Twitter @handle, rather than name being an invisible hyperlink) 
- [x] Remove the "What people are saying" section, or move it BELOW the speaker list
- [x] Optimize images (All JPG, optimized)

2020-10-30 17:21 UTC, maxxcrawford commented on site/globals/schedule.json
> +      "title": "Lightning Talks"
Should we include some sort of link for how to will work?

2020-10-30 17:31 UTC, kendallwerts commented on site/globals/schedule.json
> +      "title": "Lightning Talks"
I don't think we know that yet.

2020-10-31 20:20 UTC, kendallcorner commented
Working on Twitter handles and company names, but I'm putting the speakers up now.

2020-10-31 20:20 UTC, merged