Update Design & Add CFP Banner
techlahoma/thunderplains-2020 pull request #2
Opened 2020-09-16 19:01 UTC by matopher

This updates the overall page design and adds a banner to promote the call for proposals.

2020-09-16 19:09 UTC, matopher commented on site/includes/layouts/default.njk
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tailwindcss/ui@latest/dist/tailwind-ui.min.css">
I couldn't get the Tailwind UI plugin to play nice with our TailwindCSS setup. But once that's figured out, we can remove this.

2020-09-16 19:13 UTC, maxxcrawford requested changes
Logo tweaks. Looks great! 

Should we worry about the SASS files using the legacy `@tailwind` integration?

2020-09-17 00:47 UTC, matopher commented
> Should we worry about the SASS files using the legacy `@tailwind` integration?

@maxxcrawford Good catch. Since we're only using TailwindCSS for styling, I updated the SASS directives and rebuilt our Tailwind config. Those changes seem to have done the trick!

I _think_ we should be good to go now.

2020-09-17 03:38 UTC, kendallcorner approved these changes
Looks great!

2020-09-17 13:58 UTC, merged